name: Docker Compose CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Build and Tag images
      run: |
        docker compose -f docker-compose.yml build
    
    - name: Tag and Push backend
      run: |
        docker tag todo101-todo-backend:latest ${{ secrets.DOCKER_USERNAME }}/todo-backend:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/todo-backend:latest

    - name: Tag and Push frontend
      run: |
        docker tag todo101-todo-frontend:latest ${{ secrets.DOCKER_USERNAME }}/todo-frontend:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/todo-frontend:latest